stages:
  - lint
  - docker
  - deploy

include:
  - project: 'spacex/ci-templates'
    file: '.base.gitlab-ci.yml'


# deno镜像模板
.deno_image: &imageDef
  image: dk.uino.cn/library/denoland-deno:alpine-1.31.3

lint:
  stage: lint
  <<: *imageDef
  script:
    - deno lint src cli

docker:
  stage: docker
  extends: .docker
  variables:
    CI_DOCKERFILE: Dockerfile
    CI_DOCKER_PROJECT: deno
    CI_DOCKER_REPO: deno_proxy_server
  only:
    - tags
  script:
    - docker_build

deploy:
  stage: deploy
  variables:
    CI_DOCKER_PROJECT: deno
    CI_DOCKER_REPO: deno_proxy_server
    CI_UPGRADE_HOSTNAME: deno-mirror.uino.cn
  cache: {}
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  only:
    - tags
  script:
    - docker_deploy
