# docker-compose build 或 up
version: '3'
services:
  server:
    # image: dk.uino.cn/kiss/wiki-server:master
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./cache:/app/cache
